Repository ublue-os/bluefin-website, pull requests merged in 2025-05, with the labels that each got.

#188 feat: add ARM and LTS to the picker
  src/components/ImagePicker.vue
  src/locales/de-DE.json
  src/locales/en-US.json
  src/locales/eo.json
  src/locales/ja-JP.json
  src/locales/nl-NL.json
  src/locales/pt-BR.json
  src/locales/ru-RU.json
  src/locales/sk-SK.json
  src/locales/vi-VN.json
  src/style/index.scss
Labels: enhancement, size:L

#195 fix: typos in ISO picker making build red
  src/components/ImagePicker.vue
Labels: size:XS

#196 fix: don't show renovate on the contributors section
  public/contributors.html
Labels: size:XS, lgtm

#197 fix: make markdown rendering work and fix sizing for bluefin
  public/characters/angry.webp
  src/components/ImagePicker.vue
  src/components/scenes/SceneLanding.vue
  src/components/sections/SectionPicker.vue
  src/content.ts
  src/locales/en-US.json
Labels: size:S

#198 fix: bluefin is unavailable
  src/components/Navigation.vue
  src/components/scenes/SceneLanding.vue
  src/components/sections/SectionPicker.vue
Labels: bug, size:S

#199 fix: make build green
  src/components/Navigation.vue
  src/components/scenes/SceneLanding.vue
  src/components/sections/SectionPicker.vue
Labels: size:M

#200 revert: re-enable image-picker w/ old image handling
  src/components/ImagePicker.vue
  src/components/Navigation.vue
  src/components/scenes/SceneLanding.vue
  src/components/sections/SectionPicker.vue
Labels: size:L, lgtm

#201 fix: make build green (again)
  src/components/ImagePicker.vue
Labels: size:M

#202 fix(image-picker): make dino slightly smaller
  src/components/ImagePicker.vue
Labels: size:XS, lgtm

#213 Update de-DE.json
  src/locales/de-DE.json
Labels: documentation, size:M, lgtm
