Repository ublue-os/bluefin-website, pull requests merged in 2025-06, with the labels that each got.

#224 fix: turn off arm and lts
  src/components/ImagePicker.vue
Labels: size:XS

#231 feat: add chandeleer to art list in german & eng
  src/locales/de-DE.json
  src/locales/en-US.json
Labels: enhancement, size:XS, lgtm

#234 website: Change Artist Credit to Image Editor
  src/locales/en-US.json
Labels: size:XS, lgtm
