Repository ublue-os/bluefin-website, pull requests merged in 2025-09, with the labels that each got.

#389 chore: address text overflow on small screens
  src/style/overrides/_phone.scss
  src/style/overrides/_tablet.scss
Labels: enhancement, size:M, lgtm

#390 chore: change cron schedule to run on Mondays and Wednesdays
  .github/workflows/update-stream-versions.yml
Labels: size:XS

#394 chore: optimize graphical assets
  README.md
  index.html
  public/layer-transition.webp
  public/meta.png
  public/meta.webp
  src/components/sections/SectionMission.vue
Labels: size:XS, lgtm

#400 Update bootc link
  src/content.ts
Labels: javascript, size:XS, lgtm

#398 Add Docs Header
  package-lock.json
  package.json
  src/App.vue
  src/components/DocusaurusHeader.vue
Labels: enhancement, dependencies, javascript, size:XL

#418 Revert "Fix LTS ISO chooser workflow: move GPU selection before kernel, skip kernel question for Nvidia users"
  src/components/ImageChooser.vue
Labels: size:M

#419 feat: enhance image chooser component
  src/components/ImageChooser.vue
Labels: enhancement, size:M

#433 Remove beta flag from Bluefin lts entry
  src/components/ImageChooser.vue
Labels: size:XS
