Repository ublue-os/bluefin-website, pull requests merged in 2025-08, with the labels that each got.

#272 Update ImagePicker.vue
  src/components/ImagePicker.vue
Labels: size:XS

#284 Turn on LTS again
  src/components/ImagePicker.vue
Labels: size:XS

#281 feat: randomize landing page's top dinosaur
  src/components/scenes/SceneLanding.vue
  src/content.ts
Labels: enhancement, help wanted, javascript, size:S

#305 Replace Remaining PNG characters with WEBP versions
  public/characters/bluefin-small.png
  public/characters/bluefin-small.webp
  public/characters/devs.png
  public/characters/devs.webp
  public/characters/intrigued.png
  public/characters/intrigued.webp
  public/characters/leaping.png
  public/characters/leaping.webp
  public/characters/nest.png
  public/characters/nest.webp
  public/characters/temp.png
  public/characters/temp.webp
  src/components/ImagePicker.vue
Labels: enhancement, size:XS

#309 Resize Bluefins to ensure consistent sizing
  public/characters/angry.webp
  public/characters/intrigued.webp
  public/characters/leaping.webp
  public/characters/nest.webp
  public/characters/pride.webp
  public/characters/temp.webp
Labels: size:XS

#323 Set angry as temporary header image
  src/content.ts
Labels: size:XS, lgtm

#325 Revert "Set angry as temporary header image"
  src/content.ts
Labels: size:XS

#334 Add black outlined dinos sitewide and enable rotatin dinos
  public/characters/angry.webp
  public/characters/bluefin-small.webp
  public/characters/intrigued.webp
  public/characters/leaping.webp
  public/characters/pride.webp
  public/characters/roaring.webp
  src/content.ts
Labels: enhancement, size:XS

#337 Fix formatting in ImageChooser.vue
  src/components/ImageChooser.vue
Labels: size:XS

#347 style: add black-outlined bluefin nest and resized bluefin
  public/characters/bluefin-small.webp
  public/characters/nest.webp
  src/locales/en-US.json
Labels: size:XS

#349 chore: replace favicons with vector logo
  index.html
  public/favicons/android-chrome-192x192.png
  public/favicons/android-chrome-512x512.png
  public/favicons/apple-touch-icon.png
  public/favicons/favicon-16x16.png
  public/favicons/favicon-32x32.png
  public/favicons/favicon.svg
  public/favicons/site.webmanifest
  public/testing.html
Labels: size:S, lgtm

#352 style: replace bootc logo with vector version
  public/brands/bootc.png
  public/brands/bootc.svg
  src/content.ts
Labels: size:XS

#359 Revert "feat: Darken dinosaur background images in chooser cards for improved text legibility"
  src/components/ImageChooser.vue
  src/components/ImagePicker.vue
Labels: size:XS

#363 style: add black-outlined dinos to header and replace low definition files
  public/characters/achillobator.webp
  public/characters/angry.webp
  public/characters/bluefin-small.webp
  public/characters/dakota.webp
  public/characters/devs.webp
  public/characters/header/achillobator.webp
  public/characters/header/angry.webp
  public/characters/header/bluefin-small.webp
  public/characters/header/dakota.webp
  public/characters/header/dolly.webp
  public/characters/header/intrigued.webp
  public/characters/header/karl.webp
  public/characters/header/katharina.webp
  public/characters/header/leaping.webp
  public/characters/header/marcoventator-tai.webp
  public/characters/header/pride.webp
  public/characters/header/roaring.webp
  public/characters/header/utah.webp
  public/characters/intrigued.webp
  public/characters/leaping.webp
  public/characters/nest.webp
  public/characters/pride.webp
  public/characters/roaring.webp
  public/characters/utah.webp
Labels: enhancement, size:XS

#364 chore: resize header dinos for greater consistency
  public/characters/header/marcoventator-tai.webp
  public/characters/header/roaring.webp
Labels: size:XS

#376 Add Universal Blue logo and update footer project description
  public/brands/universal-blue.svg
  src/locales/en-US.json
  src/style/index.scss
Labels: enhancement, size:XS, lgtm

#378 chore: align and resize elements
  src/components/ImageChooser.vue
  src/style/app/sections/_footer.scss
Labels: size:XS

#381 chore: modify gradient of iso picker for readability
  src/components/ImageChooser.vue
Labels: size:S, lgtm
